spin_manifest_version = 2

[application]
name = "html-rewriter"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "html-rewriter"

[component.html-rewriter]
source = "../html-rewriter-host/target/wasm32-wasip2/release/html_rewriter_host.wasm"
allowed_outbound_hosts = ["https://developer.fermyon.com"]
[component.html-rewriter.dependencies]
"fermyon:html-rewrite/rewriter" = { path = "target/wasm32-wasip2/release/html_rewriter_rules.wasm" }
[component.html-rewriter.build]
command = ["cargo build --manifest-path ../html-rewriter-host/Cargo.toml --target wasm32-wasip2 --release", "cargo build --target wasm32-wasip2 --release"]
watch = ["src/**/*.rs", "Cargo.toml"]
