spin_manifest_version = 2

[application]
name = "html-rewriter-host"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "html-rewriter-host"

[component.html-rewriter-host]
source = "target/wasm32-wasip2/release/html_rewriter_host.wasm"
allowed_outbound_hosts = ["https://developer.fermyon.com"]
[component.html-rewriter-host.dependencies]
"fermyon:html-rewrite/rewriter" = { path = "../html-rewriter-rules/target/wasm32-wasip2/release/html_rewriter_rules.wasm" }
[component.html-rewriter-host.build]
command = ["cargo build --manifest-path ../html-rewriter-rules/Cargo.toml --target wasm32-wasip2 --release", "cargo build --target wasm32-wasip2 --release"]
watch = ["src/**/*.rs", "Cargo.toml"]
